version: '3.8'

services:
  flask-app:
    build: ./flask_app
    ports:
      - "5000:5000"
    container_name: flask_container

  django-app:
    build: ./django_app
    ports:
      - "8000:8000"
    container_name: django_container